# Generated by Django 6.0.6 on 2026-06-22 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('адрес_доставки', models.TextField(verbose_name='Адрес доставки')),
                ('телефон', models.CharField(max_length=20, verbose_name='Телефон')),
                ('дата_заказа', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('статус', models.CharField(choices=[('pending', 'В ожидании'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус')),
                ('общая_стоимость', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('пользователь', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('количество', models.PositiveIntegerField(verbose_name='Количество')),
                ('цена', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('заказ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='товары', to='shop.order', verbose_name='Заказ')),
                ('товар', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказах',
            },
        ),
    ]
